### ISSUE TITLE
ssl error 

### ISSUE THREAD

**Issue by yassinekarim** [maxisoft/Freenom-dns-updater#20] opened 2019-09-08 21:31 UTC
i get the following error 
\python37-32\lib\site-packages\requests\adapters.py", line 514, in send    
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='my.freenom.com', port=443): Max retries exceeded with url: /clientarea.php (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

**Comment by ierezell** [comment] 2019-09-14 20:32
Same for me : 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

**Comment by esrrhs** [comment] 2019-10-15 02:37
Same for me

**Comment by PShawnKD35** [comment] 2020-01-18 03:06
same issue:

shawn@DESKTOP-PShawn:~$ fdu record update test@test.com asdf test.tk -n apps
Traceback (most recent call last):
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shawn/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/shawn/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my.freenom.com', port=443): Max retries exceeded with url: /clientarea.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shawn/.local/bin/fdu", line 11, in <module>
    sys.exit(cli())
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shawn/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/shawn/.local/lib/python3.6/site-packages/freenom_dns_updater/scripts/fdu.py", line 156, in record_update
    ok_count, err_count = record_action(lambda freenom, rec: freenom.add_record(rec, True), config, False)
  File "/home/shawn/.local/lib/python3.6/site-packages/freenom_dns_updater/scripts/fdu.py", line 235, in record_action
    if not freenom.login(config.login, config.password):
  File "/home/shawn/.local/lib/python3.6/site-packages/freenom_dns_updater/freenom.py", line 33, in login
    token = self._get_login_token()
  File "/home/shawn/.local/lib/python3.6/site-packages/freenom_dns_updater/freenom.py", line 178, in _get_login_token
    return self._get_token(url)
  File "/home/shawn/.local/lib/python3.6/site-packages/freenom_dns_updater/freenom.py", line 187, in _get_token
    r = self.session.get(url)
  File "/home/shawn/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/shawn/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/shawn/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/shawn/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='my.freenom.com', port=443): Max retries exceeded with url: /clientarea.php (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

**Comment by ghost** [comment] 2020-03-07 18:33
If anybody wants a quick fix: Edit your freenom.py file, find line 187 and change the line from `r = self.session.get(url)` to `r = self.session.get(url, verify=False)`. After that reinstall the package by running `python setup.py install`. This will throw a couple of warnings when you run `fdu update` but it will work. **Note:** Using this fix will lead to a decrease in security.

**Comment by dawierha** [comment] 2020-06-20 23:57
this is fixed in my [pull request](https://github.com/maxisoft/Freenom-dns-updater/pull/22)

**Comment by maxisoft** [comment] 2020-08-11 13:07
Should be fixed by #23

**Closed as completed** 2020-08-11 13:08 UTC
